spring.main.web-application-type=none
spring.main.banner-mode=off

restoration.game.width=1280
restoration.game.height=720
restoration.game.title=Restoration
restoration.game.version=0.1.0
restoration.game.start-time-seconds=86
restoration.game.max-time-seconds=125
restoration.game.player-speed-tiles=4.3
