package pkg;

public enum EntityType {
    PLAYER,
    WALL,
    TRASH,
    QUESTION_POINT,
    DEMO_COLLECTION_ITEM,
    DEMO_QUESTION_POINT,
    DEMO_SORTING_ZONE,
    DEMO_INTAKE,
    DEMO_BIN,
    DEMO_SORTING_WASTE
}
